// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWRDt9_YlTERYKO_YIY86qXVkn5Qxt2gI',
    appId: '1:609474949205:web:b8d743e119b1d6253c64dc',
    messagingSenderId: '609474949205',
    projectId: 'fir-flutter-codelab-bda78',
    authDomain: 'fir-flutter-codelab-bda78.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-bda78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr05MAMrNW0q8o--x5a9t43CCZE7ZW0wQ',
    appId: '1:609474949205:android:db3e7cd7818b90de3c64dc',
    messagingSenderId: '609474949205',
    projectId: 'fir-flutter-codelab-bda78',
    storageBucket: 'fir-flutter-codelab-bda78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2BYkvfkjh7EAg4gugp-a-ksPrEjwUjc',
    appId: '1:609474949205:ios:89be76aff00f18263c64dc',
    messagingSenderId: '609474949205',
    projectId: 'fir-flutter-codelab-bda78',
    storageBucket: 'fir-flutter-codelab-bda78.appspot.com',
    iosClientId: '609474949205-6sh6001tn61qi2gbmo1ga3l99sji76qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2BYkvfkjh7EAg4gugp-a-ksPrEjwUjc',
    appId: '1:609474949205:ios:89be76aff00f18263c64dc',
    messagingSenderId: '609474949205',
    projectId: 'fir-flutter-codelab-bda78',
    storageBucket: 'fir-flutter-codelab-bda78.appspot.com',
    iosClientId: '609474949205-6sh6001tn61qi2gbmo1ga3l99sji76qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
